name: Build TWRP for Samsung A36

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/lib/android
        sudo apt-get clean
        df -h

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib \
          libc6-dev-i386 libncurses5 libncurses5-dev \
          x11proto-core-dev libx11-dev libgl1-mesa-dev \
          libxml2-utils xsltproc unzip fontconfig

    - name: Clone TWRP source
      run: |
        git clone https://github.com/TeamWin/android_bootable_recovery -b android-12.1 twrp
        cd twrp
        mkdir -p device/samsung
        cp -r ../device/samsung/a36xq device/samsung/

    - name: Build TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        lunch twrp_a36xq-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-A36
        path: twrp/out/target/product/a36xq/recovery.img
